######################################################################
#
# Automatically generated by qmake (3.0) ?? 8? 5 14:13:04 2016
# ref:
# http://blog.csdn.net/taiyang1987912/article/details/45642079
#
######################################################################
TARGET = dbus-server
INCLUDEPATH += .

QT += gui core widgets gui dbus

# Input
HEADERS += person.h 
SOURCES += main.cpp person.cpp

