######################################################################
#
# Automatically generated by qmake (3.0) ?? 8? 5 14:13:04 2016
# ref:
# http://blog.csdn.net/taiyang1987912/article/details/45642079
#
######################################################################

TEMPLATE = app
TARGET = server
INCLUDEPATH += .

QT += core widgets gui dbus

# Input
HEADERS += test.h test_adaptor.h
SOURCES += main.cpp test.cpp test_adaptor.cpp
